In [1]:
from model_functions import analyze_token_sequence

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
from transformers import GPT2Config, GPT2Tokenizer, GPT2LMHeadModel, DataCollatorForLanguageModeling, TrainingArguments, Trainer


# Tokeinzer

In [2]:
tokenizer = GPT2Tokenizer(
    vocab_file="vocab.json", 
    merges_file="merges.txt")

tokenizer.add_special_tokens({'pad_token': 'PAD', 'bos_token': 'BOS', 'eos_token': 'EOS',})

3

## Load model

In [3]:
model = GPT2LMHeadModel.from_pretrained(f"out/model_1/end_version")

In [4]:
inputs = tokenizer.encode("Bar_None".split(" "), return_tensors="pt")
inputs = inputs.to("cpu")
inputs

tensor([[0]])

In [5]:
outputs = model.generate(inputs, max_length=20, temperature=0.8)
outputs

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:122 for open-end generation.


tensor([[  0, 103, 118,  10,  38, 106,  10,  44, 101, 107, 118,  10,  44, 101,
         110,  12,  44, 101, 111, 118]])

In [6]:
output = model.generate(
    input_ids=inputs,
    max_length=100,  # maximum length of generated text
    do_sample=True,  # enable random sampling
    num_return_sequences=3  # number of generated sequences
)
output

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:122 for open-end generation.


tensor([[  0, 104, 119,   8,  38, 106,  13,  44, 101, 107, 118,  12,  38, 110,
          13,  44, 101, 111, 118,  15,  44, 101, 112, 119,  15,  46,   0, 104,
         119,  12,  38, 106,  13,  38, 106,  12,  38, 106,  12,  38, 106,  12,
          38, 106,  13,  38, 106,  12,  38, 106,  12,  38, 106,  13,  38, 106,
          13,  38, 106,  13,  38, 106,  13,  38, 106,  13,  38, 106,  13,  38,
         106,  13,  38, 106,  12,  38, 106,  13,  38, 106,  12,  38, 106,  13,
          38, 106,  13,  38, 106,  13,  38, 106,  12,  44, 101, 107, 118,  12,
          38, 106],
        [  0, 107,  13,  38, 109,  13,  40, 111,  13,  38, 112,  13,  38, 114,
           8,  44,   0, 103,   8,  38, 104,  15,  40, 107,  17,  38, 108,  13,
          68, 101,   0, 107,  13,  38, 111,  13,  38, 111,  13,  38, 112,  10,
          38, 111,  13,  38, 110,  20,  38, 112,  12,  38, 112,  12,  38, 112,
          12,  38, 112, 119,  10,  38, 112, 119,  13,  38, 101,   0, 103,  13,
          38, 101,   0, 103,  13

In [ ]:
inputs = tokenizer.encode("Bar_None".split(" "), return_tensors="pt")
inputs = inputs.to(device)

In [7]:
dic = {}
for idx, res in enumerate(output):
    an = analyze_token_sequence(res)
    dic[idx] = an

pd.DataFrame(dic)

0   1   2
start                                      1   1   1
start-pos                                  1   0   0
start-pos-ptriole                          0   0   0
start-pos-pitch                            0   0   1
start-pos-ptriole-pitch                    0   0   0
start-pos-pitch-duration                  20  21  11
start-pos-pitch-duration-dtriole           3   5   8
start-pos-ptriole-pitch-duration           5   1   1
start-pos-ptriole-pitch-duration-dtriole   1   1   5

In [8]:
tokens = [tensor.item() for tensor in list(outputs[0])]
tokens

[0,
 103,
 118,
 10,
 38,
 106,
 10,
 44,
 101,
 107,
 118,
 10,
 44,
 101,
 110,
 12,
 44,
 101,
 111,
 118]